##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.13.0-B3] date: [Fri Apr 16 23:17:37 CEST 2021] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = gd32vf103c-template


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
src/application/main.c \
src/application/systick.c \
src/GD32VF103_standard_peripheral/system_gd32vf103.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_adc.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_bkp.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_can.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_crc.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_dac.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_dbg.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_dma.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_eclic.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_exmc.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_exti.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_fmc.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_fwdgt.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_gpio.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_i2c.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_pmu.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_rcu.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_rtc.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_spi.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_timer.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_usart.c \
src/GD32VF103_standard_peripheral/Source/gd32vf103_wwdgt.c \
src/RISCV/drivers/n200_func.c \
src/RISCV/env_Eclipse/handlers.c \
src/RISCV/env_Eclipse/init.c \
src/RISCV/stubs/close.c \
src/RISCV/stubs/fstat.c \
src/RISCV/stubs/isatty.c \
src/RISCV/stubs/lseek.c \
src/RISCV/stubs/read.c \
src/RISCV/stubs/sbrk.c \
src/RISCV/stubs/write.c \
src/RISCV/stubs/write_hex.c \
src/RISCV/stubs/_exit.c \
src/Utilities/gd32vf103c_start.c 

# ASM sources
ASM_SOURCES =  \
src/RISCV/env_Eclipse/entry.S \
src/RISCV/env_Eclipse/start.S


#######################################
# binaries
#######################################
PREFIX = riscv-none-embed-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# mcu
MCU = -march=rv32imac -mabi=ilp32

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DGD32VF103C_START

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-Isrc/application \
-Isrc/GD32VF103_standard_peripheral \
-Isrc/GD32VF103_standard_peripheral/Include \
-Isrc/RISCV/drivers \
-Isrc/RISCV/stubs \
-Isrc/Utilities


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = src/RISCV/env_Eclipse/GD32VF103xB.lds

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -nostartfiles -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
